### ISSUE TITLE
Deploy to staging github action broken with updated action version

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/edge-proxy#91]
https://github.com/Flagsmith/edge-proxy/actions/runs/8065487035/job/22031385021#step:3:28

**Comment by gagantrivedi** [comment]
SSE moved here: https://github.com/Flagsmith/flagsmith-sse

**Comment by dabeeeenster** [comment]
This action is still broken tho?

**Comment by gagantrivedi** [comment]
> This action is still broken tho?

That workflow file does not exist any more
